[build]
  command = "pip install -r requirements.txt && python app.py"  # Build command to install dependencies and start the app

[build.environment]
  PYTHON_VERSION = "3.9"  # Specify the desired Python version
